### ISSUE TITLE
Migrate to Yarn from NPM

### ISSUE THREAD

**Issue by meganindya** [sugarlabs/musicblocks-v4-lib#102]
## Description

The project currently uses NPM for dependency management. However, Yarn is generally faster than NPM. Migrate the usage of NPM to Yarn.

## Objectives

- [ ] Replace `package-lock.json` with `yarn.lock`
  - install yarn locally (`npm i -g yarn`)
  - remove `node_modules` folder and `package-lock.json` file, then run `yarn install`
- [ ] Update `Dockerfile`
  - remove NPM update step
  - replace `npm install -g` steps with `yarn global add`
- [ ] Update GitHub Actions CI workflow steps
  - replace `run: npm ci` with `run: yarn install --frozen-lockfile`
  - enable step `run: yarn run build`
  - replace `run: npm run test --if-present` with `run: yarn run test`
  - Update comment from `Run npm scripts` to `Run yarn scripts`
- [ ] Update `README.md`
  - replace `npm` based instructions to `yarn` based instructions

This may be completed through 4 separate PRs.

**Comment by RishiKumarRay** [comment]
looks amazing , I want to try this , assign me

**Comment by bvdbasch** [comment]
Hi 👋🏻

I have submitted a PR. I saw that the previous PR from [@Gri-ffin](https://github.com/Gri-ffin) was rejected due to merge conflicts. As it currently stands, the branch in this PR should not result in any merge issues. However, GitHub action results are pending, as running them need to be approved first and I did not have the time to configure them on my fork. 

Hope this helps and have a nice day 👍🏻
