### ISSUE TITLE
Remove error status in keySignature.ts

### ISSUE THREAD

**Issue by meganindya** [sugarlabs/musicblocks-v4-lib#46]
On branch [`musicutils`](https://github.com/sugarlabs/musicblocks-v4-lib/tree/musicutils), TypeScript ported file [`keySignature.ts`](https://github.com/sugarlabs/musicblocks-v4-lib/blob/musicutils/src/.prototype/musicutils/ts/keySignature.ts) has methods which return success/failure status.

Is it possible to do without them? Default cases during failures have been replaced by `Error` subclass instances in #45. Please discuss the possibility here before proceeding.

**Comment by ksraj123** [comment]
Currently, The errors are returned as the last item in the array, a number which could take value either 0 or -1 denoting if there is an error or not. The value is checked where the function is being called. This was a simple approach to error handling and could be done using try catch. Instead of returning the error we  can throw it with defaultValues and catch it in the catch block and depending upon the type of error we may execute different instructions. Currently wherever -1 is being returned we are already throwing an error so we could refactor it to execute error checking instructions in catch. If there is a situation where a function can throw more than one type of error with different error codes then we might want to use different types of errors there or maybe introduce a new error type. Also currently the error checks for functions which return error codes is not done consistently, that should be improved as well. Currently error codes are returned by the following functions in `keySignature.ts`. Thanks

        closestNote
        convertToGenericNoteName
        _genericNoteNameToLetterName
        _convertFromNoteName
        _findMoveable
        _genericNoteNameToSolfege
        _genericNoteNameToEastIndianSolfege
        _genericNoteNameToScalarModeNumber
        _genericNoteNameToCustomNoteName
        semitoneTransform
        scalarTransform
        scalarDistance
